name: Check code styles

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup node env
        uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: [API] Run code style Prettier check
        run: yarn run style:format:api

      - name: [API] Run code style ESLint check
        run: yarn run style:format:web

      - name: [WEB] Run code style Prettier check
        run: yarn run style:lint:web

      - name: [WEB] Run code style ESLint check
        run: yarn run style:lint:api